version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-management
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  homework-network:
