server:
  port : 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/users/**

discovery:
  client:
    simple:
      instances:
        auth-service:
          - uri: http://localhost:8081
        user-management:
          - uri: http://localhost:8082
